server:
  port: 8080
  servlet:
    context-path: /api
  compression:
    enabled: true # Whether response compression is enabled.
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json # Comma-separated list of MIME types that should be compressed.
    min-response-size: 1024 # Minimum "Content-Length" value that is required for compression to be performed.
  undertow:
    threads:
      worker: 64 # Generally this should be reasonably high, at least 10 per CPU core: https://undertow.io/undertow-docs/undertow-docs-2.1.0/index.html#listeners-2
      io: 4 # One IO thread per CPU core is a reasonable default: https://undertow.io/undertow-docs/undertow-docs-2.1.0/index.html#listeners-2

spring:
  application.name: spring-postgres-template
  datasource:
    url: jdbc:mysql://${mysql.url}/${postgres.schema}?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${postgres.username}
    password: ${postgres.password}
    hikari:
      auto-commit: false
      connection-timeout: 250 # It is a millisecond setting. The ideal is to keep it low so that the timeout elapses soon and does not tie up the threads.
      max-lifetime: 600000 # Maximum time a connection can be open (10 min) - security.
      maximum-pool-size: 20 # We maintain a maximum of 20 connections to the database. The ideal is to keep it low, as it is something costly for the bank to manage. https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing
      minimum-idle: 10 # We maintain a minimum of 10 connections to the database.
      pool-name: master
  jpa:
    open-in-view: false # Opens a connection (transaction) with the database from the controller.
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      "[hibernate.dialect]": org.hibernate.dialect.MySQLDialect
      "[hibernate.generate_statistics]": false
      "[hibernate.connection.provider_disables_autocommit]": true
      # To maximize performance, we disabled auto-commit and open-in-view.
      # https://vladmihalcea.com/why-you-should-always-use-hibernate-connection-provider_disables_autocommit-for-resource-local-jpa-transactions/